### ISSUE TITLE
[suggestion] Add parameter to wait for cluster to become ready

### ISSUE THREAD

**Issue by eshepelyuk** [AbsaOSS/k3d-action#14]
Hello.

Is it possible to add some check, so the action would wait until cluster becomes "ready".

Apparently, "readiness" is quite ambigous term, but maybe some minimal condition could be defined and added to docs, 
so users of this action will have to create less boilerplate code like, `sleep` \ bash loops etc in their GitHub workflows.

**Comment by k0da** [comment]
Hi,
@eshepelyuk k3d already waits for cluster to be ready:
```      --wait                                                           Wait for the server(s) to be ready before returning. Use '--timeout DURATION' to not wait forever. (default true)```
Is this not enough for your case?

**Comment by eshepelyuk** [comment]
Hi,

I'm using `wait: true` in my k3d config YAML. 

```yaml
options:
  k3d:
    wait: true
```

But, after `$ k3d cluster create ..` returns, I'm calling `$ kubectl get nodes` and nodes status is not yet `Ready`.
And I have to add `sleep 20` hack, like below

```yaml
      - uses: AbsaOSS/k3d-action@v1.2.0
        name: "Create Single Cluster"
        with:
          cluster-name: "k3d"
          args: >-
            --config ./k3d.yaml
      - name: Nodes
        run: |
          sleep 20
          kubectl config use-context k3d-k3d
          kubectl get nodes -o wide
```

I assume `--wait` only checks id docker images are already ran, but not that k8s cluster is up and accesible.
