### ISSUE TITLE
[feat] possibility to override k3s image

### ISSUE THREAD

**Issue by eshepelyuk** [AbsaOSS/k3d-action#19]
It is impossible to use custom k3s because

* When passed via k3d `--config` yaml file, it's ignored because explicitely declared via cmd line argument ro `k3d cluster create`
* When passed via action `input.args` it is also ignored because explicitely overrden by action cmd line 

Suggestions
* If passed k3d yaml config is used, parse the file and try to retrieve k3s version from it.
* If pased via `input.args` parse argument and override the k3s image
* Otherwise, used default action version

**Comment by kuritka** [comment]
@ninuxio, @eshepelyuk, @k0da 

k3d-action v1.4.0 was just released. Default k3s version functioanlity was removed.

To use specific k3s image use `--image` argument or update config yaml:

```yaml
# example:  via argument
      - name: Create single node k3s cluster
        uses: AbsaOSS/k3d-action@v1.4.0
        with:
          cluster-name: "test-gslb1"
          use-default-registry: false
          args: >-
            --agents 1
            --image docker.io/rancher/k3s:v1.20.5-k3s1  # <<<<
```

```yaml
# example: via config yaml
apiVersion: k3d.io/v1alpha2
kind: Simple
name: test-gslb1
image: docker.io/rancher/k3s:v1.20.5-k3s1 # <<<<
...
```

For further details read [version mapping](https://github.com/AbsaOSS/k3d-action#version-mapping).
